export const pulseSkillOptions = [
  'Accounting',
  'Advanced Excel',
  'AI Tools',
  'Analytics',
  'Brand Management',
  'Budgeting',
  'Business Communication',
  'Business Development',
  'Business Research',
  'Business Strategy',
  'Canva',
  'Case Solving',
  'Client Management',
  'Competitive Analysis',
  'Consulting',
  'Content Strategy',
  'Copywriting',
  'CRM',
  'Customer Discovery',
  'Dashboarding',
  'Data Analysis',
  'Data Visualization',
  'Design Thinking',
  'Digital Marketing',
  'Due Diligence',
  'Email Marketing',
  'Entrepreneurship',
  'Equity Research',
  'Event Management',
  'Financial Analysis',
  'Financial Modeling',
  'Financial Planning',
  'Forecasting',
  'Fundraising',
  'Go-to-Market Strategy',
  'Growth Marketing',
  'HR Analytics',
  'Investment Analysis',
  'Leadership',
  'LinkedIn Outreach',
  'Market Research',
  'Marketing Analytics',
  'Negotiation',
  'Operations Management',
  'Pitch Decks',
  'Portfolio Management',
  'Power BI',
  'PowerPoint',
  'Presentation Design',
  'Pricing Strategy',
  'Problem Solving',
  'Product Management',
  'Project Management',
  'Public Speaking',
  'Python',
  'Recruitment',
  'Relationship Management',
  'Research Writing',
  'Resume Writing',
  'Sales',
  'Search Engine Optimization',
  'Social Media Marketing',
  'SQL',
  'Stakeholder Management',
  'Startup Strategy',
  'Storytelling',
  'Tableau',
  'Team Management',
  'UX Research',
  'Valuation',
  'Venture Capital Research'
];

export const pulseInterestOptions = [
  'AI and Automation',
  'Banking',
  'Brand Building',
  'Business Case Competitions',
  'Campus Communities',
  'Climate and Sustainability',
  'Consulting',
  'Consumer Brands',
  'Creator Economy',
  'Data and Analytics',
  'Design',
  'Digital Products',
  'E-commerce',
  'EdTech',
  'Entrepreneurship',
  'Equity Research',
  'Finance',
  'FinTech',
  'Freelance Projects',
  'General Management',
  'Growth and Marketing',
  'Healthcare',
  'Human Resources',
  'Impact Consulting',
  'Investment Banking',
  'Live Projects',
  'Luxury and Retail',
  'Market Research',
  'Marketing',
  'Media and Entertainment',
  'Operations',
  'Personal Branding',
  'Placement Preparation',
  'Portfolio Building',
  'Product Management',
  'Public Policy',
  'Research',
  'Resume Building',
  'Sales',
  'Social Impact',
  'Startups',
  'Strategy',
  'Supply Chain',
  'Technology',
  'Venture Capital'
];
