-- Expand ATS role profiles with differentiated, level-specific keyword and verb banks.
-- This migration intentionally updates profile data only; resume/JD text remains browser-only.

with
  role_profile_seed as (
    select *
    from (
      values
        ('data_analyst', array['sql','excel','power bi','tableau','python','dashboard','data cleaning','data visualization','statistics','kpi','reporting','business intelligence','eda','pivot tables','vlookup','data quality','data storytelling','insights','metrics','trend analysis'], array['excel projects','sql joins','data cleaning project','coursework analytics','spreadsheet dashboards','python basics','statistics coursework','college project'], array['internship analytics','power bi dashboard','tableau dashboard','sql queries','python pandas','eda project','business reporting','data validation','certification'], array['stakeholder reporting','recurring dashboards','automation','cohort analysis','variance analysis','data governance','ad hoc analysis','root cause analysis','data model'], array['metric ownership','dashboard governance','analytics roadmap','experimentation','self-service reporting','data strategy','cross-functional insights','data quality framework'], array['analyzed','cleaned','visualized','reported','segmented','validated','automated','modeled','tracked','interpreted'], array['summary','skills','projects','experience','education','certifications']),
        ('business_analyst', array['requirements','stakeholder management','process mapping','user stories','brd','frd','gap analysis','acceptance criteria','use cases','sql','excel','dashboard','process improvement','uat','documentation','wireframes','business process','jira','confluence','impact analysis'], array['requirements workshop','process mapping project','case study','excel analysis','user story practice','college project','documentation sample','basic sql'], array['internship project','stakeholder notes','user stories','acceptance criteria','uat support','process documentation','business case','dashboard'], array['requirement ownership','process redesign','solution validation','uat coordination','change request','impact assessment','cross-functional delivery','business metrics'], array['business architecture','operating model','transformation roadmap','executive reporting','benefit realization','process governance','portfolio prioritization','strategic initiatives'], array['gathered','documented','mapped','analyzed','prioritized','validated','coordinated','improved','translated','facilitated'], array['summary','skills','projects','experience','education','certifications']),
        ('data_scientist', array['python','machine learning','statistics','regression','classification','pandas','numpy','scikit-learn','sql','model evaluation','feature engineering','eda','data preprocessing','hypothesis testing','nlp','clustering','time series','model deployment','jupyter','matplotlib'], array['ml coursework','python notebooks','statistics project','kaggle','data preprocessing','basic regression','classification project','eda portfolio'], array['internship model','feature engineering','model metrics','cross validation','sql extraction','python pipeline','classification','regression','data storytelling'], array['production model','model monitoring','ab testing','feature store','experiment design','model explainability','stakeholder insights','ml pipeline'], array['ml strategy','model governance','advanced experimentation','forecasting ownership','recommendation systems','deployment architecture','mentoring','research translation'], array['modeled','predicted','trained','evaluated','engineered','optimized','validated','analyzed','experimented','deployed'], array['summary','skills','projects','experience','education','publications']),
        ('hr_generalist', array['recruitment','onboarding','employee engagement','hr operations','ats','payroll','policy','screening','interviewing','hrms','employee relations','performance management','learning and development','attendance','grievance handling','offer letters','hr analytics','compliance','talent acquisition','exit formalities'], array['campus hiring support','screening practice','hr internship','employee engagement project','onboarding checklist','hr coursework','interview coordination'], array['recruitment funnel','candidate screening','joining formalities','hrms data','employee engagement','policy documentation','attendance tracking','offer rollout'], array['recruitment ownership','stakeholder hiring','employee relations','hr dashboards','policy implementation','performance cycle','payroll coordination','retention initiatives'], array['people strategy','workforce planning','talent programs','manager coaching','hr governance','engagement strategy','attrition analysis','process transformation'], array['recruited','screened','onboarded','coordinated','resolved','implemented','tracked','organized','facilitated','advised'], array['summary','skills','experience','projects','education','certifications']),
        ('marketing_associate', array['campaigns','brand','content','market research','lead generation','seo','social media','analytics','copywriting','crm','positioning','audience segmentation','go-to-market','competitive research','email campaigns','content calendar','campaign reporting','creative brief','conversion','customer insights'], array['content calendar','market research project','social media campaign','copywriting samples','college fest marketing','brand audit','survey analysis'], array['campaign execution','crm lists','email campaign','content writing','social media analytics','lead generation','seo basics','market research'], array['campaign ownership','brand messaging','conversion tracking','cross-channel planning','audience segmentation','marketing automation','campaign roi','creative testing'], array['brand strategy','gtm planning','portfolio campaigns','budget ownership','growth strategy','team leadership','market positioning','marketing analytics'], array['launched','created','researched','positioned','promoted','tracked','generated','optimized','tested','planned'], array['summary','skills','experience','projects','education','portfolio']),
        ('digital_marketing_specialist', array['seo','sem','google ads','meta ads','email marketing','analytics','conversion','ctr','cpc','roas','content marketing','landing page','keyword research','google analytics','search console','a/b testing','retargeting','utm','paid social','marketing automation'], array['seo audit','keyword research','content optimization','social analytics','google analytics basics','ad copy practice','landing page review'], array['campaign internship','google ads','meta ads','email campaign','utm tracking','seo implementation','content calendar','performance dashboard'], array['performance marketing','roas optimization','conversion rate optimization','retargeting','budget pacing','funnel analysis','landing page testing','channel mix'], array['growth engine','media strategy','attribution model','lifecycle marketing','marketing ops','budget ownership','agency management','scaling campaigns'], array['optimized','launched','scaled','tested','converted','tracked','segmented','improved','targeted','reported'], array['summary','skills','experience','projects','certifications','portfolio']),
        ('finance_analyst', array['financial analysis','budgeting','forecasting','variance analysis','excel','financial reporting','kpi','reconciliation','power bi','profit and loss','cash flow','working capital','month end close','management reporting','financial planning','cost analysis','mis','scenario analysis','business finance','sap'], array['excel modeling','finance coursework','ratio analysis','budget template','case competition','p&l basics','financial statement project'], array['budget support','variance report','mis reporting','reconciliation','forecast update','excel dashboard','month end support','sap basics'], array['forecast ownership','budget cycle','business partnering','cost optimization','working capital analysis','management reporting','scenario model','variance commentary'], array['fp&a leadership','strategic planning','board reporting','business unit finance','investment cases','forecast governance','margin improvement','finance transformation'], array['forecasted','analyzed','reconciled','modeled','reported','budgeted','tracked','evaluated','prepared','reviewed'], array['summary','skills','experience','projects','education','certifications']),
        ('financial_analyst', array['financial modeling','valuation','forecasting','excel','financial statements','variance analysis','dcf','ratio analysis','reporting','comparable companies','sensitivity analysis','scenario analysis','cash flow','profitability','capex','opex','investment analysis','corporate finance','powerpoint','research'], array['valuation project','dcf coursework','financial statement analysis','excel model','ratio analysis','case study','finance club'], array['financial model','forecast assumptions','company research','valuation comps','sensitivity table','reporting pack','investment memo'], array['model ownership','management reporting','investment case','forecast model','scenario analysis','valuation support','executive deck','business performance'], array['strategic finance','capital allocation','deal analysis','valuation governance','portfolio decisions','senior stakeholder reporting','model review','mentoring analysts'], array['modeled','valued','forecasted','analyzed','reported','benchmarked','evaluated','prepared','recommended','presented'], array['summary','skills','experience','projects','education','certifications']),
        ('investment_banking_analyst', array['valuation','dcf','comps','pitchbook','financial modeling','m&a','transaction','due diligence','excel','powerpoint','precedent transactions','teaser','information memorandum','deal execution','capital markets','lbo','merger model','industry research','client presentation','data room'], array['valuation case','pitch deck sample','dcf project','transaction comps','finance society','excel modeling','industry research'], array['pitchbook support','valuation model','deal research','buyer list','comps update','due diligence tracker','presentation formatting','transaction analysis'], array['deal execution','financial model ownership','client materials','process management','due diligence coordination','valuation analysis','transaction memorandum','sector coverage'], array['deal leadership','origination support','client advisory','model review','negotiation support','transaction strategy','junior mentoring','execution management'], array['valued','modeled','prepared','researched','analyzed','supported','benchmarked','drafted','coordinated','executed'], array['summary','skills','experience','projects','education','certifications']),
        ('equity_research_analyst', array['equity research','valuation','financial statements','sector research','dcf','comps','investment thesis','earnings','ratio analysis','financial modeling','target price','recommendation','industry analysis','channel checks','forecasting','broker reports','annual report','company analysis','market share','catalysts'], array['stock pitch','sector report','annual report analysis','valuation project','investment thesis','finance club','earnings summary'], array['coverage support','earnings update','model update','sector tracker','company note','valuation comps','news monitoring','investment memo'], array['coverage ownership','earnings preview','forecast model','target price update','investment recommendation','sector deep dive','client note','management call'], array['lead coverage','portfolio recommendations','thematic research','institutional client insights','model governance','junior review','sector strategy','high conviction calls'], array['researched','valued','modeled','recommended','tracked','analyzed','forecasted','published','initiated','updated'], array['summary','skills','experience','projects','education','certifications']),
        ('credit_analyst', array['credit risk','loan assessment','financial statements','cash flow','debt service','covenants','underwriting','risk rating','borrower analysis','collateral','credit memo','ratio analysis','repayment capacity','default risk','portfolio monitoring','banking','limit assessment','due diligence','stress testing','policy'], array['credit case study','ratio analysis','banking coursework','borrower profile','financial statement review','credit memo sample'], array['credit appraisal','borrower documents','cash flow analysis','risk rating','covenant tracking','credit memo','loan file review','portfolio data'], array['underwriting ownership','credit recommendation','portfolio monitoring','early warning signals','collateral review','sector risk','limit renewal','policy compliance'], array['credit policy','portfolio risk strategy','large exposure review','risk governance','team review','stress framework','committee presentation','credit portfolio leadership'], array['assessed','reviewed','rated','analyzed','monitored','validated','recommended','documented','underwrote','approved'], array['summary','skills','experience','projects','education','certifications']),
        ('risk_analyst', array['risk management','market risk','credit risk','operational risk','controls','compliance','var','stress testing','reporting','risk register','risk assessment','mitigation','internal controls','loss events','regulatory reporting','model risk','scenario analysis','audit','incident management','governance'], array['risk case study','control testing','risk register','compliance coursework','scenario analysis','audit project'], array['risk reporting','control checklist','loss data','compliance monitoring','risk assessment','incident log','stress test support','dashboard'], array['risk ownership','control remediation','risk metrics','regulatory submission','operational risk framework','scenario analysis','audit coordination','policy review'], array['enterprise risk','risk appetite','governance forums','regulatory strategy','risk transformation','senior reporting','framework ownership','team mentoring'], array['identified','measured','monitored','mitigated','tested','reported','assessed','escalated','controlled','remediated'], array['summary','skills','experience','projects','education','certifications']),
        ('portfolio_analyst', array['portfolio management','asset allocation','performance attribution','risk','benchmark','returns','investment analysis','reporting','portfolio monitoring','rebalancing','fund analysis','aum','alpha','beta','tracking error','drawdown','security selection','investment policy','client reporting','market commentary'], array['portfolio project','asset allocation simulation','return analysis','benchmark study','investment club','performance report'], array['portfolio report','fund research','performance tracker','asset allocation','risk metrics','market update','benchmark analysis','client deck'], array['portfolio monitoring','rebalancing support','attribution analysis','manager research','investment committee material','risk review','client reporting','allocation model'], array['portfolio strategy','allocation governance','investment committee leadership','multi-asset analysis','manager selection','performance review ownership','client advisory','junior mentoring'], array['monitored','allocated','analyzed','reported','benchmarked','evaluated','rebalanced','tracked','recommended','reviewed'], array['summary','skills','experience','projects','education','certifications']),
        ('accounting_audit_analyst', array['accounting','audit','reconciliation','internal controls','gaap','ifrs','ledger','compliance','financial statements','trial balance','journal entries','statutory audit','internal audit','tax audit','working papers','accounts payable','accounts receivable','fixed assets','variance','sap'], array['accounting coursework','audit checklist','reconciliation project','journal entries','ledger review','case study'], array['audit support','working papers','reconciliation','voucher testing','ledger review','control testing','financial statement support','documentation'], array['audit ownership','control testing','month end close','variance review','compliance checklist','client coordination','statutory schedules','process improvement'], array['audit planning','control framework','team supervision','technical accounting','client advisory','risk-based audit','process governance','review management'], array['audited','reconciled','verified','tested','prepared','reviewed','documented','controlled','closed','examined'], array['summary','skills','experience','projects','education','certifications']),
        ('tax_analyst', array['tax compliance','gst','tds','income tax','filing','returns','tax research','reconciliation','documentation','direct tax','indirect tax','tax audit','advance tax','withholding tax','transfer pricing','notices','assessment','tax computation','sap','excel'], array['tax coursework','gst basics','tds calculation','return filing project','tax research note','compliance calendar'], array['gst filing','tds return','tax computation','reconciliation','notice support','documentation','compliance tracker','tax audit support'], array['compliance ownership','tax provision','assessment support','gst reconciliation','withholding review','process improvement','advisory memo','stakeholder coordination'], array['tax strategy','litigation support','compliance governance','planning advisory','team review','policy interpretation','risk management','process automation'], array['filed','prepared','reviewed','reconciled','researched','computed','documented','validated','advised','submitted'], array['summary','skills','experience','projects','education','certifications'])
    ) as seed(role_key, base_keywords, internship_keywords, fresher_keywords, entry_level_keywords, experienced_keywords, verbs, sections)
  ),
  tech_and_business_seed as (
    select *
    from (
      values
        ('software_developer', array['javascript','typescript','react','node.js','api','database','git','testing','debugging','system design','data structures','algorithms','rest api','unit testing','ci cd','deployment','clean code','performance','security','agile'], array['coding assignments','github projects','dsa basics','web app project','api basics','debugging practice','college project'], array['internship feature','bug fixes','unit tests','api integration','git workflow','responsive ui','database queries','deployment basics'], array['feature ownership','code review','test coverage','api design','performance optimization','production debugging','sprint delivery','technical documentation'], array['architecture','system design','mentoring','scalability','technical leadership','design review','incident resolution','platform ownership'], array['built','implemented','debugged','optimized','tested','integrated','refactored','deployed','designed','shipped'], array['summary','skills','projects','experience','education','github']),
        ('frontend_developer', array['react','javascript','typescript','html','css','accessibility','responsive design','state management','performance','ui','redux','next.js','vite','tailwind','design system','browser compatibility','api integration','web vitals','forms','component library'], array['portfolio website','html css project','react basics','responsive layout','figma to code','javascript practice','github'], array['frontend internship','component development','api integration','responsive fixes','accessibility basics','state management','browser testing','ui polish'], array['feature ownership','component architecture','performance optimization','design system','accessibility audits','frontend testing','cross-browser support','release delivery'], array['frontend architecture','design system governance','web performance strategy','technical mentoring','platform migration','accessibility leadership','frontend standards','team reviews'], array['built','implemented','styled','optimized','tested','integrated','improved','shipped','prototyped','validated'], array['summary','skills','projects','experience','education','github']),
        ('backend_developer', array['node.js','api','database','sql','postgres','authentication','authorization','performance','testing','deployment','rest api','microservices','queues','caching','logging','monitoring','security','orm','serverless','cloud'], array['api project','sql basics','backend coursework','authentication demo','database schema','node basics','github'], array['backend internship','api endpoints','database queries','bug fixes','auth integration','unit tests','deployment support','logging'], array['service ownership','database optimization','api design','security controls','background jobs','observability','integration reliability','incident support'], array['backend architecture','distributed systems','scalability','platform reliability','security governance','technical leadership','service standards','mentoring'], array['designed','built','integrated','optimized','secured','tested','deployed','maintained','monitored','scaled'], array['summary','skills','projects','experience','education','github']),
        ('full_stack_developer', array['react','node.js','typescript','api','database','postgres','authentication','testing','deployment','git','full stack','frontend','backend','rest api','responsive design','cloud','ci cd','product features','debugging','integration'], array['full stack project','portfolio app','frontend basics','backend basics','database schema','github','college project'], array['internship feature','frontend backend integration','api consumption','bug fixes','auth flow','database queries','deployment','testing'], array['end-to-end feature ownership','technical design','api contract','frontend performance','backend reliability','test coverage','release ownership','product collaboration'], array['platform architecture','system design','technical leadership','cross-stack standards','mentoring','scalability','product engineering strategy','delivery governance'], array['built','integrated','implemented','optimized','tested','deployed','debugged','delivered','designed','owned'], array['summary','skills','projects','experience','education','github']),
        ('product_manager', array['roadmap','requirements','user research','metrics','prioritization','stakeholders','product strategy','experiments','analytics','prd','user stories','backlog','go-to-market','customer discovery','market research','wireframes','kpi','a/b testing','launch','product lifecycle'], array['product case study','user research project','prd sample','market research','wireframe','college product project','analytics basics'], array['product internship','prd draft','user interviews','backlog grooming','metric tracking','competitive analysis','feature brief','launch support'], array['feature ownership','roadmap input','stakeholder alignment','experiment design','kpi ownership','customer insights','prioritization framework','delivery coordination'], array['product strategy','roadmap ownership','portfolio prioritization','team leadership','commercial impact','market expansion','executive alignment','product governance'], array['defined','prioritized','launched','researched','measured','aligned','coordinated','validated','discovered','owned'], array['summary','skills','experience','projects','education','case studies']),
        ('sales_associate', array['sales','lead generation','pipeline','crm','cold calling','negotiation','revenue','demo','closing','prospecting','qualification','discovery call','objection handling','follow up','conversion','account management','targets','salesforce','hubspot','proposal'], array['sales internship','cold outreach practice','crm basics','college sales event','pitch deck','lead list','role play'], array['prospecting','qualified leads','crm hygiene','demo support','follow ups','pipeline update','sales calls','target achievement'], array['quota ownership','pipeline management','negotiation','account growth','conversion rate','sales forecasting','territory planning','proposal ownership'], array['revenue ownership','team targets','strategic accounts','sales process improvement','coaching','enterprise deals','forecast governance','relationship management'], array['generated','prospected','qualified','pitched','negotiated','closed','followed up','converted','forecasted','expanded'], array['summary','skills','experience','projects','education','achievements']),
        ('business_development_associate', array['business development','partnerships','lead generation','outreach','pipeline','crm','market research','proposal','revenue','alliances','channel partners','strategic partnerships','prospecting','account mapping','negotiation','growth','deal sourcing','networking','commercials','relationship management'], array['bd internship','market mapping','outreach list','partnership case','proposal sample','crm basics','college initiative'], array['lead generation','outreach campaigns','partner research','proposal support','crm updates','meeting coordination','pipeline support','market analysis'], array['partnership ownership','pipeline generation','commercial proposal','negotiation support','channel development','market expansion','revenue tracking','stakeholder management'], array['strategic partnerships','new market entry','alliance strategy','revenue leadership','partner ecosystem','deal structuring','team mentoring','growth strategy'], array['identified','generated','pitched','partnered','negotiated','expanded','converted','researched','sourced','developed'], array['summary','skills','experience','projects','education','achievements']),
        ('operations_associate', array['operations','process improvement','coordination','sop','reporting','workflow','inventory','vendor','quality','excel','process mapping','sla','tat','compliance','daily operations','issue resolution','automation','cost reduction','resource planning','dashboards'], array['operations internship','sop draft','excel tracker','process map','college event operations','vendor coordination','quality checklist'], array['daily operations','sop execution','tracker maintenance','vendor follow up','issue log','reporting','inventory update','coordination'], array['process ownership','workflow improvement','sla tracking','automation','cost saving','quality control','vendor management','operations dashboard'], array['operations strategy','process governance','team leadership','capacity planning','transformation initiatives','cost optimization','cross-functional operations','operating cadence'], array['coordinated','streamlined','tracked','improved','implemented','resolved','documented','monitored','standardized','reduced'], array['summary','skills','experience','projects','education','certifications']),
        ('project_manager', array['project planning','stakeholder management','timeline','risk management','budget','delivery','status reporting','jira','agile','scope','milestones','resource planning','dependency management','change management','project governance','raid log','pmo','communication plan','delivery metrics','client management'], array['project coordination','college project','timeline tracker','risk log','meeting notes','planning coursework','presentation'], array['project internship','status updates','meeting coordination','jira tickets','timeline tracking','risk log','documentation','stakeholder follow up'], array['project delivery','scope management','dependency tracking','risk mitigation','budget tracking','stakeholder reporting','change control','delivery cadence'], array['program management','portfolio governance','strategic delivery','team leadership','executive reporting','budget ownership','delivery transformation','pmo standards'], array['planned','delivered','coordinated','tracked','mitigated','managed','reported','aligned','scheduled','escalated'], array['summary','skills','experience','projects','education','certifications']),
        ('scrum_master', array['scrum','agile','sprint planning','retrospective','daily standup','jira','impediments','velocity','team facilitation','kanban','backlog refinement','burndown','servant leadership','agile coaching','ceremonies','capacity planning','continuous improvement','delivery health','team metrics','release planning'], array['agile coursework','scrum simulation','jira basics','team project','retrospective notes','sprint board','certification prep'], array['ceremony support','jira updates','sprint tracking','impediment log','retrospective actions','team coordination','velocity reporting','backlog support'], array['ceremony ownership','impediment removal','team coaching','velocity improvement','delivery predictability','stakeholder alignment','agile metrics','continuous improvement'], array['agile transformation','multi-team facilitation','delivery governance','coach product teams','release train','agile maturity','leadership coaching','team health strategy'], array['facilitated','coached','removed','tracked','improved','coordinated','reported','enabled','guided','unblocked'], array['summary','skills','experience','projects','education','certifications']),
        ('consulting_analyst', array['consulting','market research','problem solving','excel','powerpoint','stakeholder','strategy','analysis','recommendations','issue tree','hypothesis','benchmarking','market sizing','client presentation','business case','financial analysis','primary research','secondary research','storyboarding','implementation'], array['consulting case','market sizing','case competition','powerpoint deck','research project','excel analysis','problem structuring'], array['client research','benchmarking','excel model','slide deck','interview notes','data analysis','recommendation memo','case work'], array['workstream ownership','client-ready output','hypothesis testing','business case','stakeholder interviews','implementation roadmap','financial analysis','executive deck'], array['engagement leadership','client advisory','strategy roadmap','operating model','team management','senior stakeholder management','transformation leadership','proposal development'], array['analyzed','researched','recommended','modeled','presented','structured','benchmarked','synthesized','diagnosed','advised'], array['summary','skills','experience','projects','education','case studies']),
        ('management_consulting_analyst', array['strategy','operating model','market sizing','benchmarking','financial analysis','powerpoint','excel','client','recommendations','transformation','cost optimization','growth strategy','organization design','process improvement','business case','implementation roadmap','workstream','executive presentation','competitive analysis','value creation'], array['strategy case','market sizing','operating model study','case competition','deck building','excel model','business case'], array['consulting internship','market research','benchmark analysis','client deck','data model','workstream support','recommendation slide','stakeholder notes'], array['workstream delivery','operating model design','business case ownership','client workshop','implementation planning','value tracking','executive presentation','process redesign'], array['engagement management','transformation strategy','client relationship','team leadership','proposal leadership','value realization','senior advisory','portfolio transformation'], array['structured','analyzed','benchmarked','recommended','presented','modeled','synthesized','diagnosed','facilitated','transformed'], array['summary','skills','experience','projects','education','case studies']),
        ('strategy_analyst', array['strategy','market research','competitive analysis','business model','growth','forecasting','kpi','financial analysis','market sizing','pricing','unit economics','go-to-market','scenario planning','strategic initiatives','business case','corporate strategy','industry trends','white space','partnerships','investment thesis'], array['strategy project','market sizing','competitor analysis','business model canvas','case study','research report','forecast exercise'], array['strategy internship','market research','competitor tracker','growth analysis','business case support','kpi dashboard','industry scan','gtm research'], array['strategic initiative','growth model','market entry analysis','scenario planning','executive reporting','pricing analysis','business case ownership','competitive intelligence'], array['corporate strategy','portfolio strategy','m&a support','growth roadmap','executive alignment','strategic planning cycle','team leadership','investment recommendations'], array['analyzed','researched','forecasted','recommended','evaluated','benchmarked','prioritized','modeled','sized','framed'], array['summary','skills','experience','projects','education','case studies']),
        ('customer_success_associate', array['customer success','onboarding','retention','adoption','crm','support','renewal','churn','customer health','nps','csat','account management','product adoption','customer journey','qbr','ticket resolution','knowledge base','upsell','relationship management','usage analytics'], array['customer support internship','crm basics','onboarding checklist','service project','customer research','support scripts','case study'], array['customer onboarding','ticket resolution','crm updates','health score tracking','adoption follow up','renewal support','customer calls','knowledge base'], array['account ownership','retention initiatives','qbr support','churn risk mitigation','product adoption','customer health dashboard','upsell coordination','stakeholder management'], array['customer success strategy','renewal ownership','portfolio management','expansion revenue','team coaching','customer lifecycle design','executive relationships','retention governance'], array['onboarded','supported','retained','resolved','tracked','improved','renewed','educated','expanded','advised'], array['summary','skills','experience','projects','education','achievements']),
        ('supply_chain_analyst', array['supply chain','procurement','inventory','logistics','demand planning','vendor','forecasting','fulfillment','excel','erp','warehouse','transportation','stockouts','safety stock','purchase order','s&op','lead time','cost optimization','supplier management','service level'], array['supply chain project','inventory model','forecast exercise','vendor comparison','logistics case','excel tracker','operations coursework'], array['inventory tracking','po support','vendor follow up','demand forecast','logistics coordination','erp update','stock report','fulfillment tracker'], array['demand planning','supplier performance','inventory optimization','cost reduction','service level analysis','s&op support','warehouse metrics','process improvement'], array['supply chain strategy','network optimization','procurement governance','vendor negotiation','planning leadership','cost transformation','s&op ownership','team mentoring'], array['forecasted','planned','optimized','tracked','coordinated','reduced','monitored','analyzed','procured','reconciled'], array['summary','skills','experience','projects','education','certifications']),
        ('ui_ux_designer', array['ui design','ux research','wireframes','prototyping','figma','user flows','usability testing','design system','persona','journey mapping','interaction design','visual design','information architecture','accessibility','responsive design','user interviews','heuristic evaluation','prototype testing','component library','product design'], array['portfolio project','figma prototype','wireframe practice','user research assignment','design critique','college app redesign','case study'], array['design internship','user flows','wireframes','prototype','usability test','figma components','research synthesis','portfolio case'], array['feature design ownership','design system contribution','user research planning','accessibility review','prototype testing','product metrics','developer handoff','interaction patterns'], array['design strategy','design system governance','research leadership','product vision','team mentoring','experience architecture','cross-functional design leadership','quality standards'], array['designed','researched','prototyped','tested','mapped','iterated','validated','improved','facilitated','shipped'], array['summary','skills','portfolio','projects','experience','education'])
    ) as seed(role_key, base_keywords, internship_keywords, fresher_keywords, entry_level_keywords, experienced_keywords, verbs, sections)
  ),
  all_seed as (
    select * from role_profile_seed
    union all
    select * from tech_and_business_seed
  ),
  level_seed as (
    select *
    from (
      values
        ('internship', array['coursework','academic project','capstone','internship','learning mindset','tools basics','guided project','portfolio project','certification','team project'], array['assisted','learned','supported','researched','prepared','organized','documented','practiced'], 'Show coursework, projects, tools exposure, and willingness to learn through concrete project evidence.', 'Academic projects, internships, certifications, portfolio work, and measurable project outputs.', 'Avoid generic objectives; add project context, tools used, and what changed because of your work.'),
        ('fresher', array['internship','project','certification','portfolio','tool proficiency','business problem','measurable outcome','team collaboration','presentation','entry role'], array['created','built','analyzed','coordinated','delivered','improved','presented','completed'], 'Show practical readiness through internships, strong projects, certifications, and clear tool usage.', 'Internship outcomes, academic projects, live projects, certifications, case competitions, and measurable results.', 'Avoid listing tools without proof; connect each skill to a project, internship, or result.'),
        ('entry_level', array['ownership','stakeholder','process improvement','reporting cadence','business impact','automation','production exposure','client communication','quality improvement','cross-functional'], array['owned','delivered','improved','automated','coordinated','resolved','implemented','reported'], 'Show role ownership, repeatable work, stakeholder collaboration, and measurable business impact.', 'Professional experience, owned deliverables, dashboards, shipped features, process improvements, and stakeholder outcomes.', 'Avoid task-only bullets; quantify scope, frequency, business impact, and responsibility.'),
        ('experienced', array['strategy','leadership','governance','mentoring','roadmap','scalability','executive reporting','transformation','team leadership','domain expertise'], array['led','owned','mentored','scaled','transformed','governed','strategized','directed'], 'Show depth, ownership, leadership, measurable outcomes, and domain maturity.', 'Owned programs, team leadership, strategic initiatives, cost/revenue impact, governance, and cross-functional leadership.', 'Avoid junior task framing; emphasize decision ownership, scale, leadership, and business outcomes.')
    ) as seed(level_key, level_keywords, level_verbs, summary, evidence, warning)
  ),
  expanded as (
    select
      r.id as role_id,
      l.id as level_id,
      level_seed.level_key,
      all_seed.role_key,
      all_seed.sections,
      level_seed.summary,
      level_seed.evidence,
      level_seed.warning,
      (
        select array_agg(distinct lower(keyword) order by lower(keyword))
        from unnest(
          all_seed.base_keywords ||
          case level_seed.level_key
            when 'internship' then all_seed.internship_keywords
            when 'fresher' then all_seed.fresher_keywords
            when 'entry_level' then all_seed.entry_level_keywords
            else all_seed.experienced_keywords
          end ||
          level_seed.level_keywords
        ) as keyword
      ) as keywords,
      (
        select array_agg(distinct lower(verb) order by lower(verb))
        from unnest(all_seed.verbs || level_seed.level_verbs) as verb
      ) as action_verbs
    from all_seed
    join level_seed on true
    join public.ats_roles r on r.role_key = all_seed.role_key
    join public.ats_role_levels l on l.level_key = level_seed.level_key
  )
insert into public.ats_role_profiles (role_id, level_id, keywords, action_verbs, preferred_sections, expectations, scoring_weights)
select
  expanded.role_id,
  expanded.level_id,
  expanded.keywords,
  expanded.action_verbs,
  expanded.sections,
  jsonb_build_object(
    'level', expanded.level_key,
    'summary', expanded.summary,
    'evidence', expanded.evidence,
    'warning', expanded.warning,
    'keyword_strategy', 'Role keywords are expanded by role, career level, and maturity expectations. Students should include only truthful, evidence-backed terms.'
  ),
  '{}'::jsonb
from expanded
on conflict (role_id, level_id) do update
set
  keywords = excluded.keywords,
  action_verbs = excluded.action_verbs,
  preferred_sections = excluded.preferred_sections,
  expectations = excluded.expectations,
  updated_at = now();
